name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  examples_build_and_test:
    strategy:
      fail-fast: false
      matrix:
        example:
          [
            eth-pm,
            relay-angular-chat,
            relay-reactjs-chat,
            store-reactjs-chat,
            web-chat
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "*/package-lock.json"

      - name: install
        run: npm ci
        working-directory: ${{ matrix.example }}

      - name: build
        run: npm run build
        working-directory: ${{ matrix.example }}

      - name: test
        run: npm run test --if-present
        working-directory: ${{ matrix.example }}
