name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  examples_build_and_test:
    strategy:
      fail-fast: false
      matrix:
        example:
          [
            web-chat,
            eth-pm,
            eth-pm-wallet-encryption,
            relay-reactjs-chat,
            store-reactjs-chat,
            relay-angular-chat,
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
          cache-dependency-path: "*/pnpm-lock.yaml"

      - name: install
        run: pnpm install --frozen-lockfile
        working-directory: ${{ matrix.example }}

      - name: test
        run: pnpm run test
        working-directory: ${{ matrix.example }}
